#!/bin/bash
# Script: system_info.sh
# Purpose: Display system information
# Author: Kajal

# # exit on error
# set -e

# #variable
# HOSTNAME=$(hostname)
# DATE=$(date)

# #Main logic
# echo "========System info======"
# echo "Hostname = $HOSTNAME"
# echo "Date: $DATE"
# echo "Uptime: $(uptime -p)"
# echo "Disk Usage: $(df -h) / | awk 'NR==2 {print $5}')"


# $ ./system_info.sh
# ========System info======
# Hostname = KAJAL
# Date: Sat, Jan 31, 2026  2:07:06 PM
# ./system_info.sh: line 17: uptime: command not found
# Uptime: 
# Disk Usage: Filesystem      Size  Used Avail Use% Mounted on
# E:/Prog/Git     101G   70G   31G  70% /
# C:              277G  214G   63G  78% /c
# D:              101G   58G   43G  58% /d / | awk 'NR==2 {print }')


#Create a script that displays useful system information:
# system_info.sh- Display system information

echo "==================================="
echo "
System Information Report"
echo "==================================="
echo ""
echo "Date and Time:"
echo " $(date)"
echo ""
echo "System:"
echo " Hostname: $(hostname)"
echo " OS: $(uname -s)"
echo " Kernel: $(uname -r)"
echo ""
echo "User:"
echo " Current user: $(whoami)"
echo " Home directory: $HOME"
echo " Shell: $SHELL"
echo ""
echo "System Load:"
echo " Uptime: $(uptime -p 2>/dev/null || uptime)"
echo ""
echo "Disk Usage:"
df -h / | awk 'NR==1 {print " " $0} NR==2 {print " " $0}'
echo ""
echo "Memory:"
free -h 2>/dev/null | awk 'NR==1 {print " " $0} NR==2 {print " " $0}' || echo " (memory info not available)"
echo ""
echo "==================================="
echo "Report generated by: $0"
echo "==================================="