name: ECS build and push to ECR

on:
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  ECR_REGISTRY: 292659698930.dkr.ecr.us-east-1.amazonaws.com
  ECR_REPOSITORY: jan26-bootcamp-student-portal
  IMAGE_TAG: ${{ github.sha }}
  APP_PATH: Week-6/student-portal

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug structure
        run: ls -R

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image
        working-directory: ${{ env.APP_PATH }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

  ecs-deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    env:
      ecs_cluster: jan26-bootcamp-student-portal
      ecs_service: jan26-bootcamp-student-portal-service
      ecs_task_definition: jan26-bootcamp-student-portal-task
      new_image: 292659698930.dkr.ecr.ap-south-1.amazonaws.com/jan26-bootcamp-student-portal:${{ github.sha }}

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Download task definition
        run: aws ecs describe-task-definition \
          --task-definition ${{ env.ecs_task_definition }} \
          --query taskDefinition > task-definition.json

      - name: Update task definition
        run: |
          jq --arg IMAGE "${{ env.new_image }}" \
          '.containerDefinitions[0].image = $IMAGE' \
          task-definition.json > updated.json
          mv updated.json task-definition.json

      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: task-definition.json
          service: ${{ env.ecs_service }}
          cluster: ${{ env.ecs_cluster }}
          wait-for-service-stability: true