name: Week6 ECS terraform apply

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  Terraform_version: 1.14.7
  infra_path: Week-7/infra

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6 
      - name: Debug repo structure
        run: |
          pwd
          ls -R
      - name: configure-aws-credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: ${{ env.Terraform_version }}

      - name: Initialize Terraform
        working-directory: ${{ env.infra_path }}
        run: terraform init

      - name: Apply Terraform configuration
        working-directory: ${{ env.infra_path }}
        run: terraform apply -auto-approve
  